-- Lua bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/CircularTextMac/CircularTextMac/AppDelegate.h
-- Generated by Celedev® LuaBindingsGenerator on 2015-09-16 15:53:46 +0000



-- Objective C interface: @interface AppDelegate
local AppDelegate = objc.classInterface ("AppDelegate") --[[ @inherits NSObject, @protocols NSApplicationDelegate]]
