-- Lua bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/CircularTextMac/CircularTextMac/ViewController.h
-- Generated by Celedev® LuaBindingsGenerator on 2015-09-29 10:26:33 +0000



-- Objective C interface: @interface ViewController
local ViewController = objc.classInterface ("ViewController") --[[ @inherits NSViewController]]
